# Generated by Django 4.0 on 2022-01-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pic', models.CharField(max_length=50)),
                ('kontak_pic', models.IntegerField(max_length=11)),
            ],
        ),
    ]
