# Generated by Django 4.0 on 2022-01-21 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0004_surat'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_user', models.CharField(max_length=50)),
                ('password_user', models.CharField(max_length=25)),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.role')),
            ],
        ),
    ]
