# Generated by Django 4.0 on 2022-01-21 12:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0005_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='kontak_pic',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.CreateModel(
            name='Disposisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_disposisi', models.DateField()),
                ('keterangan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.keterangan')),
                ('surat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.surat')),
            ],
        ),
    ]
