# Generated by Django 4.0 on 2022-01-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0006_alter_pic_kontak_pic_disposisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='surat',
            name='nomorSurat',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
