# Generated by Django 4.0 on 2022-01-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0007_surat_nomorsurat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='nama_pic',
            new_name='instansiAsal',
        ),
        migrations.RenameField(
            model_name='pic',
            old_name='kontak_pic',
            new_name='kontakPic',
        ),
        migrations.AddField(
            model_name='pic',
            name='namaPic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
