# Generated by Django 4.0 on 2022-01-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0008_rename_nama_pic_pic_instansiasal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pic',
            old_name='instansiAsal',
            new_name='instansi_asal',
        ),
        migrations.RenameField(
            model_name='pic',
            old_name='kontakPic',
            new_name='kontak_pic',
        ),
        migrations.RenameField(
            model_name='pic',
            old_name='namaPic',
            new_name='nama_pic',
        ),
        migrations.RenameField(
            model_name='surat',
            old_name='estimasiDeadline',
            new_name='estimasi_deadline',
        ),
        migrations.RenameField(
            model_name='surat',
            old_name='nomorSurat',
            new_name='nomor_surat',
        ),
        migrations.RenameField(
            model_name='surat',
            old_name='tanggalMasuk',
            new_name='tanggal_masuk',
        ),
        migrations.RenameField(
            model_name='surat',
            old_name='tanggalSurat',
            new_name='tanggal_surat',
        ),
    ]
