# Generated by Django 4.0.1 on 2022-02-03 07:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0009_rename_instansiasal_pic_instansi_asal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposisi1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_disposisi', models.DateField()),
                ('catatan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disposisi2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_disposisi', models.DateField()),
                ('catatan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disposisi3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_disposisi', models.DateField()),
                ('catatan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disposisi4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_disposisi', models.DateField()),
                ('catatan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jabatan', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='surat',
            name='pic_id',
        ),
        migrations.AddField(
            model_name='surat',
            name='email_pic',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='surat',
            name='file_surat',
            field=models.FileField(null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='surat',
            name='id_pic',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='surat',
            name='instansi_asal',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='surat',
            name='kontak_pic',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AddField(
            model_name='surat',
            name='nama_pic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='keterangan',
            name='keterangan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='nama_role',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='surat',
            name='tanggal_masuk',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nama_user',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Disposisi',
        ),
        migrations.DeleteModel(
            name='Pic',
        ),
        migrations.AddField(
            model_name='disposisi4',
            name='keterangan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.keterangan'),
        ),
        migrations.AddField(
            model_name='disposisi4',
            name='surat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.surat'),
        ),
        migrations.AddField(
            model_name='disposisi4',
            name='tujuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.jabatan'),
        ),
        migrations.AddField(
            model_name='disposisi3',
            name='keterangan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.keterangan'),
        ),
        migrations.AddField(
            model_name='disposisi3',
            name='surat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.surat'),
        ),
        migrations.AddField(
            model_name='disposisi3',
            name='tujuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.jabatan'),
        ),
        migrations.AddField(
            model_name='disposisi2',
            name='keterangan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.keterangan'),
        ),
        migrations.AddField(
            model_name='disposisi2',
            name='surat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.surat'),
        ),
        migrations.AddField(
            model_name='disposisi2',
            name='tujuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.jabatan'),
        ),
        migrations.AddField(
            model_name='disposisi1',
            name='keterangan_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.keterangan'),
        ),
        migrations.AddField(
            model_name='disposisi1',
            name='surat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.surat'),
        ),
        migrations.AddField(
            model_name='disposisi1',
            name='tujuan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.jabatan'),
        ),
    ]
