# Generated by Django 4.0.1 on 2022-02-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0010_disposisi1_disposisi2_disposisi3_disposisi4_jabatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='file_surat',
            field=models.FileField(null=True, upload_to='surat/'),
        ),
    ]
