# Generated by Django 4.0.1 on 2022-02-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0011_alter_surat_file_surat'),
    ]

    operations = [
        migrations.AddField(
            model_name='surat',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
