# Generated by Django 4.0.1 on 2022-02-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0012_surat_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi1',
            name='tanggal_disposisi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
