# Generated by Django 4.0.1 on 2022-03-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0013_alter_disposisi1_tanggal_disposisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposisi1',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disposisi2',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disposisi3',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='disposisi2',
            name='tanggal_disposisi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='disposisi3',
            name='tanggal_disposisi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
