# Generated by Django 4.0.1 on 2022-03-15 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0014_disposisi1_status_disposisi2_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surat',
            name='id_pic',
        ),
    ]
