# Generated by Django 4.0.1 on 2022-03-15 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0015_remove_surat_id_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_keluar', models.CharField(max_length=50)),
                ('keterangan_disposisi1', models.CharField(max_length=50)),
                ('catatan_disposisi1', models.CharField(max_length=50, null=True)),
                ('keterangan_disposisi2', models.CharField(max_length=50)),
                ('catatan_disposisi2', models.CharField(max_length=50, null=True)),
                ('keterangan_disposisi3', models.CharField(max_length=50)),
                ('catatan_disposisi3', models.CharField(max_length=50, null=True)),
                ('upload_luaran', models.FileField(null=True, upload_to='luaran/')),
                ('nomor_masuk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.surat')),
            ],
        ),
        migrations.AlterField(
            model_name='disposisi1',
            name='catatan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disposisi2',
            name='catatan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='disposisi3',
            name='catatan',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Disposisi4',
        ),
    ]
