# Generated by Django 4.0.1 on 2022-03-17 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0016_luaran_alter_disposisi1_catatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi2',
            name='surat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.disposisi1'),
        ),
    ]
