# Generated by Django 4.0.1 on 2022-03-17 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0017_alter_disposisi2_surat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi3',
            name='surat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.disposisi2'),
        ),
        migrations.AlterField(
            model_name='luaran',
            name='nomor_masuk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elisaapp.disposisi3'),
        ),
    ]
