# Generated by Django 4.0.1 on 2022-03-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0018_alter_disposisi3_surat_id_alter_luaran_nomor_masuk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi1',
            name='catatan',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
