# Generated by Django 4.0.1 on 2022-03-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0020_alter_disposisi1_catatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposisi1',
            name='catatan',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
