# Generated by Django 4.0.1 on 2022-03-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0024_alter_disposisi1_catatan_alter_disposisi2_catatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luaran',
            name='upload_luaran',
            field=models.FileField(blank=True, null=True, upload_to='luaran/'),
        ),
    ]
