# Generated by Django 4.0.1 on 2022-03-30 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0025_alter_luaran_upload_luaran'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
