# Generated by Django 4.0.1 on 2022-04-02 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elisaapp', '0027_delete_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luaran',
            name='catatan_disposisi1',
        ),
        migrations.RemoveField(
            model_name='luaran',
            name='catatan_disposisi2',
        ),
        migrations.RemoveField(
            model_name='luaran',
            name='catatan_disposisi3',
        ),
        migrations.RemoveField(
            model_name='luaran',
            name='keterangan_disposisi1',
        ),
        migrations.RemoveField(
            model_name='luaran',
            name='keterangan_disposisi2',
        ),
        migrations.RemoveField(
            model_name='luaran',
            name='keterangan_disposisi3',
        ),
    ]
